### PR TITLE
Misc minor changes

### PR DESCRIPTION
**Pull request by rodnymolina**

### CODE REVIEW

**Comment by EddieX64** [comment]
Hi @rodnymolina Just FYI there is a mistake on https://github.com/nestybox/sysbox-pkgr/blob/master/k8s/scripts/sysbox-deploy-k8s.sh#L793
The version 1.29 became 1.20. I just tested installation of sysbox v0.6.5 on GKE 1.29 and It's broken.

**Review by ctalledo — APPROVED** [review]
LGTM, thanks!

**Comment by ctalledo** [comment]
Agree with @EddieX64 , there's a mistake (typo) that we must fix to enable K8s v1.29, and then re-generate the sysbox-deploy-k8s daemonset images.

**Comment by rodnymolina** [comment]
Thank you @EddieX64 and @ctalledo, I just fixed it.

**Pull request merged**
